add equation list to cartersian_graph
SE-691-Graphing-Calculator/cartesian_graph pull request #6
Opened 2020-11-29 16:30 UTC by nvthblake

2020-11-29 16:32 UTC, nvthblake commented
@gwarchol Hey Greg, somehow the build failed because pubspec.yaml file is missing but I have the file on my branch, so I am not sure why the error showing up. Can you help me check? Thank you.

2020-11-29 19:10 UTC, gwarchol requested changes

2020-11-29 19:10 UTC, gwarchol commented on example/.dart_tool/package_config.json
> +{
file seems unnecessary

2020-11-29 19:10 UTC, gwarchol commented on example/.flutter-plugins
> +# This is a generated file; do not edit or check into version control.
should not be committed

2020-11-29 19:10 UTC, gwarchol commented on example/.flutter-plugins-dependencies
> +{"info":"This is a generated file; do not edit or check into version control.","plugins":{"ios":[{"name":"cartesian_graph","path":"D:\\\\Users\\\\nvthblake\\\\Github\\\\cartesian_graph\\\\","dependen
should not be committed

2020-11-29 19:10 UTC, gwarchol commented on example/.packages
> +# Generated by pub on 2020-11-08 10:33:17.986178.
should not be committed

2020-11-29 19:10 UTC, gwarchol commented on example/pubspec.lock
> +# Generated by pub
should not be committed

2020-11-29 19:10 UTC, gwarchol commented on lib/cartesian_graph.dart
> +        AdvancedCalculator calculator = createCoordinateCalculator();
this should only occur once, not multiple times

2020-11-29 19:10 UTC, gwarchol commented on pubspec.lock
> +# Generated by pub
should not be committed

2020-11-29 19:10 UTC, gwarchol commented on lib/cartesian_graph.dart
> +    for (int i = 0; i < equations.length; i++) {
please add test for multiple equation scenario

2020-12-01 01:04 UTC, gwarchol commented
> 
> 
> @gwarchol Hey Greg, somehow the build failed because pubspec.yaml file is missing but I have the file on my branch, so I am not sure why the error showing up. Can you help me check? Thank you.

2020-12-01 01:05 UTC, gwarchol commented
00:11 +1 -10: /home/runner/work/cartesian_graph/cartesian_graph/cartesian_graph/test/cartesian_graph_test.dart: Segment plotting plots equation display coordinates with equation [E] is the build failure

2020-12-03 20:18 UTC, merged

2020-12-03 20:25 UTC, gwarchol commented
@nvthblake this is still missing tests